<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Metrodata Academy_w-9 h-9 lgw-10 lgh_1e0ff3</name>
   <tag></tag>
   <elementGuidId>7ff2434b-e943-476f-9323-50ba8fe81151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[4]/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^1999$/ >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>467e8cab-0c0e-4c0c-9f92-e24ea9b16b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-9 h-9 lg:w-10 lg:h-10 flex items-center justify-center relative bg-[#EFEFEF] rounded-full font-semibold text-white</value>
      <webElementGuid>b52c485d-12fc-4346-a9d0-158fb1ecfe8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;p-8 lg:py-24 xl:px-[108px]&quot;]/div[@class=&quot;flex flex-col items-center justify-center gap-5 mx-auto max-w-7xl&quot;]/div[@class=&quot;flex justify-between w-full&quot;]/div[@class=&quot;relative flex flex-col justify-center items-center w-full before:bg-[#EFEFEF] before:absolute before:-z-10 before:w-full before:h-[3px] before:right-2/4 before:top-1/3 before:-translate-y-2/4 false&quot;]/button[@class=&quot;w-9 h-9 lg:w-10 lg:h-10 flex items-center justify-center relative bg-[#EFEFEF] rounded-full font-semibold text-white&quot;]</value>
      <webElementGuid>3973c47b-f1b7-482e-a301-6bc235d04e33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[4]/div/div/div[2]/button</value>
      <webElementGuid>e46cd1b2-bd75-437c-ae91-2f358036cc6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>5e120fb1-8579-46d9-8b46-987e3ce71e52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
