<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Keuntungan yang kamu dapatkan di Metrod_aa6bd5</name>
   <tag></tag>
   <elementGuidId>d26adc26-91b7-444f-a9ec-f86ea9c8c0ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Keuntungan yang kamu dapatkan di Metrodata IT-Camp'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.bg-cerulean-100.rounded-lg.p-3.h-12.w-12.flex-shrink-0.fill-cerulean-600</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^TrainingTraining selama kurang lebih 3 bulan dengan kelas tertentu\.$/ >> svg</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>deff7f00-f7a3-45ac-9596-5fb29cfd024d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>b77c633e-cd76-441d-88f4-4da509d933a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>796feefb-7606-4c13-a6e5-804be067e697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dfd652d5-e842-4478-8d71-3c7407c220f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 20 20</value>
      <webElementGuid>8aac46bf-01eb-47b8-973c-5efcceb8d000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c1e0bc1b-9e6c-40c4-99a5-83e2cc320f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-cerulean-100 rounded-lg p-3 h-12 w-12 flex-shrink-0 fill-cerulean-600</value>
      <webElementGuid>43af6e1a-5c94-4f9d-9d66-d35d33883a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>7c348374-479a-4201-91b7-d0f3f5f68de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>893fb75a-71c5-40c4-a30c-239bc2556c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>98688827-8f29-4c50-99c7-e426177d3618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;p-8 lg:py-24 lg:px-[108px] bg-cerulean-50&quot;]/div[@class=&quot;flex flex-col items-center bg-cerulean-50&quot;]/div[@class=&quot;flex items-center justify-center&quot;]/div[@class=&quot;w-full grid md:grid-cols-2 lg:grid-cols-3 gap-5&quot;]/div[@class=&quot;max-h-72 sm:max-h-72 rounded-lg bg-white shadow p-6 flex flex-col&quot;]/svg[@class=&quot;bg-cerulean-100 rounded-lg p-3 h-12 w-12 flex-shrink-0 fill-cerulean-600&quot;]</value>
      <webElementGuid>7e0c8080-8957-4e54-82f3-0ca379d5aca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keuntungan yang kamu dapatkan di Metrodata IT-Camp'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>d248a165-1e3c-4a04-bf21-e2ccfcd1866f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrodata Security Camp'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>8bfb3b97-047d-4d51-8b56-de6ff108a94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>be229915-0b3c-43a9-9e22-e169100d7934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peluang Menjadi Karyawan'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>7aa3912b-cccb-48c0-b83f-85234fe5082e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
