<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_PilihKotaKABUPATEN</name>
   <tag></tag>
   <elementGuidId>433f957b-4577-42ee-8a88-4fdaeff3fa49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#city</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a8e6763a-5b27-4481-ba25-1d0552486974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>d0d2fbae-c656-4028-8db8-6bdf9dff0c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>f4086a0f-cae2-4be3-a3dc-7145c9db8f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full pl-3 pr-8 py-[14px] bg-gray-50 border border-gray-300 rounded-lg truncate</value>
      <webElementGuid>5585afca-eded-44bb-b9fe-a1b8a1aec6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih KotaKABUPATEN KEPULAUAN SERIBUKOTA JAKARTA SELATANKOTA JAKARTA TIMURKOTA JAKARTA PUSATKOTA JAKARTA BARATKOTA JAKARTA UTARA</value>
      <webElementGuid>9b3e14cd-a421-46b8-a3fc-4b2f97e5dff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)</value>
      <webElementGuid>10e497f1-4850-4c23-ad78-53c354105342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='city']</value>
      <webElementGuid>09e2a389-b4ef-4c4b-9ff2-476ffd7e8431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/div/div[2]/div/div[8]/div/select</value>
      <webElementGuid>d16e64bb-96b4-4647-b633-3257d432d14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>f9bce9eb-117b-4a3d-886f-ba5f15932da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[1]/preceding::select[1]</value>
      <webElementGuid>b4d84fa0-40ac-4746-9af9-8850c9b85928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>4ec34f8a-6ed1-4a33-b3db-37174711c736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'city' and @name = 'city' and (text() = 'Pilih KotaKABUPATEN KEPULAUAN SERIBUKOTA JAKARTA SELATANKOTA JAKARTA TIMURKOTA JAKARTA PUSATKOTA JAKARTA BARATKOTA JAKARTA UTARA' or . = 'Pilih KotaKABUPATEN KEPULAUAN SERIBUKOTA JAKARTA SELATANKOTA JAKARTA TIMURKOTA JAKARTA PUSATKOTA JAKARTA BARATKOTA JAKARTA UTARA')]</value>
      <webElementGuid>4ad5caa1-9d32-4048-94bc-8b3e647c3ed6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
