<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Provinsi</name>
   <tag></tag>
   <elementGuidId>f47561bc-eb48-449c-a442-a8972a1961f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='province']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#province</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5bc3f0ff-3381-42e3-a831-79846cb28fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>province</value>
      <webElementGuid>e7bcac8f-dbb0-4dea-a1a0-00f4848213f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>province</value>
      <webElementGuid>6190f38d-85fb-4fd9-babe-9e7a24f5fd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full pl-3 pr-8 py-[14px] bg-gray-50 border border-gray-300 rounded-lg truncate</value>
      <webElementGuid>dc1226eb-bd24-47d2-8fe7-8bde64ffc0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih ProvinsiACEHSUMATERA UTARASUMATERA BARATRIAUJAMBISUMATERA SELATANBENGKULULAMPUNGKEPULAUAN BANGKA BELITUNGKEPULAUAN RIAUDKI JAKARTAJAWA BARATJAWA TENGAHDI YOGYAKARTAJAWA TIMURBANTENBALINUSA TENGGARA BARATNUSA TENGGARA TIMURKALIMANTAN BARATKALIMANTAN TENGAHKALIMANTAN SELATANKALIMANTAN TIMURKALIMANTAN UTARASULAWESI UTARASULAWESI TENGAHSULAWESI SELATANSULAWESI TENGGARAGORONTALOSULAWESI BARATMALUKUMALUKU UTARAPAPUA BARATPAPUA</value>
      <webElementGuid>4e0e096a-955d-4f61-acc1-2435b0354a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;province&quot;)</value>
      <webElementGuid>e460d23a-9b3c-465a-ac7a-cd15bfa95f26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='province']</value>
      <webElementGuid>9e2b1640-9987-476e-a060-be8a46406106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/div/div[2]/div/div[7]/div/select</value>
      <webElementGuid>70832b13-0b71-4d91-a555-1cc5c67ac9c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>f22f90fc-22bc-4ed0-8ea0-af19e429a7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>a79d084a-6aa3-4075-9cb0-af8eaa2e26b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/select</value>
      <webElementGuid>43d11f53-0099-46a1-b96f-2001d95498fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'province' and @name = 'province' and (text() = 'Pilih ProvinsiACEHSUMATERA UTARASUMATERA BARATRIAUJAMBISUMATERA SELATANBENGKULULAMPUNGKEPULAUAN BANGKA BELITUNGKEPULAUAN RIAUDKI JAKARTAJAWA BARATJAWA TENGAHDI YOGYAKARTAJAWA TIMURBANTENBALINUSA TENGGARA BARATNUSA TENGGARA TIMURKALIMANTAN BARATKALIMANTAN TENGAHKALIMANTAN SELATANKALIMANTAN TIMURKALIMANTAN UTARASULAWESI UTARASULAWESI TENGAHSULAWESI SELATANSULAWESI TENGGARAGORONTALOSULAWESI BARATMALUKUMALUKU UTARAPAPUA BARATPAPUA' or . = 'Pilih ProvinsiACEHSUMATERA UTARASUMATERA BARATRIAUJAMBISUMATERA SELATANBENGKULULAMPUNGKEPULAUAN BANGKA BELITUNGKEPULAUAN RIAUDKI JAKARTAJAWA BARATJAWA TENGAHDI YOGYAKARTAJAWA TIMURBANTENBALINUSA TENGGARA BARATNUSA TENGGARA TIMURKALIMANTAN BARATKALIMANTAN TENGAHKALIMANTAN SELATANKALIMANTAN TIMURKALIMANTAN UTARASULAWESI UTARASULAWESI TENGAHSULAWESI SELATANSULAWESI TENGGARAGORONTALOSULAWESI BARATMALUKUMALUKU UTARAPAPUA BARATPAPUA')]</value>
      <webElementGuid>90059a6c-1323-45a7-866e-0a29ec20a5cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
