<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PilihUniversitas</name>
   <tag></tag>
   <elementGuidId>9bbc0d95-7241-46ed-8aea-fbd8c1792b02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='university']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#university</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>278eaf28-c190-45ca-b81e-5b010a973b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>university</value>
      <webElementGuid>72346322-97d6-4867-92fd-538fe5cdf720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>university</value>
      <webElementGuid>9c9f44a9-e2b1-47e4-b792-306799266bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full px-3 py-[14px] bg-gray-50 border border-gray-300 rounded-lg</value>
      <webElementGuid>a5acdb2d-f704-4222-b895-7d63575f8f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih UniversitasUniversitas StikubankInstitut Sains dan Teknologi Al KamalUniversitas Sanata DharmaUniversitas Kristen MaranathaUniversitas JemberPoliteknik Elektronika Negeri SurabayaSTMIK Nusa MandiriUniversitas Teknologi MataramUniversitas Jendral SoedirmanInstitut Teknologi Sepuluh NovemberUniversitas BrawijayaUniversitas Pakuan BogorUniversitas Ibn Khaldun BogorUniversitas Budi LuhurPoliteknik Pos IndonesiaPoliteknik Negeri JakartaUniversitas Pendidikan IndonesiaUniversitas Islam IndonesiaInstitut Bisnis dan Informatika Stikom SurabayaUniversitas MulawarmanUniversitas GunadarmaUniversitas TarumanegaraSekolah Tinggi Teknik - Perusahaan Listrik NegaraUniversitas Muhammadiyah SukabumiSTMIK RaharjaUniversitas TrilogiLainnyaUniversitas IndonesiaInstitut Pertanian BogorUniversitas Muhammadiyah MalangInstitut Teknologi PLNUniversitas AndalasUniversitas Muhammadiyah JakartaUniversitas Pembangunan Nasional Veteran YogyakartaUniversitas PGRI SemarangUniversitas Islam Negeri Sunan Gunung Djati BandungUniversitas LampungUniversitas Mercu BuanaPoliteknik Negeri MalangUniversitas PGRI IndraprastaUniversitas PadjajaranPoliteknik Negeri SriwijayaSTMIK MikroskilUniversitas YarsiUniversitas NasionalPresident UniversityUniversitas SurabayaUniversitas Islam Negeri Syarif Hidayatullah JakartaUniversitas Pembangunan Nasional Veteran SurabayaUniversitas CiputraUniversitas Sunan KalijagaUniversitas DiponegoroUniversitas Ahmad DahlanUniversitas Amikom YogyakartaPoliteknik Pertanian Negeri SamarindaUniversitas Dian NuswantoroUniversitas Negeri JakartaUniversitas SriwijayaPoliteknik CaltexUniversitas Indraprasta PgriSTMIK Ikmi CirebonInstitut Bisnis dan Informatika Kwik Kian GieUniversitas Muhammadiyah YogyakartaUniversitas TelkomUniversitas Gadjah MadaUniversitas Kristen Satya WacanaInstitut Teknologi DelSTMIK Pasim Al-FathUniversitas Teknologi YogyakartaInstitut Teknologi Nasional MalangUniversitas PamulangInstitut KalbisUniversitas SingaperbangsaUniversitas Kristen Duta WacanaUniversitas Bina NusantaraSTMIK Asia MalangUniversitas Darma PersadaUniversitas Muhammadiyah PurwokertoSTMIK Widya PratamaUniversitas Negeri YogyakartaInstitut Teknologi BandungUniversitas UdayanaUniversitas Bina Sarana InformatikaPoliteknik Negeri BandungUniversitas BengkuluUniversitas Atma JayaUniversitas Putra Indonesia YPTK PadangUniversitas Sumatra Utara</value>
      <webElementGuid>c96ab6b1-ffa1-4599-b0a3-ea191f0d4c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;university&quot;)</value>
      <webElementGuid>523b9cc7-7ffb-4c76-a6a3-2091dc801647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='university']</value>
      <webElementGuid>9487d952-f54d-445f-bc7e-ddc22b83bac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>83539191-a799-400a-bdb6-aaead2ea454e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
      <webElementGuid>7c8fa232-3c75-45cc-a7a2-305128da0c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/preceding::select[1]</value>
      <webElementGuid>db374a2a-d548-4e42-8bc0-669a13145c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>57dc6a70-d5bd-4aa1-bb35-65f8ddf25711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'university' and @id = 'university' and (text() = 'Pilih UniversitasUniversitas StikubankInstitut Sains dan Teknologi Al KamalUniversitas Sanata DharmaUniversitas Kristen MaranathaUniversitas JemberPoliteknik Elektronika Negeri SurabayaSTMIK Nusa MandiriUniversitas Teknologi MataramUniversitas Jendral SoedirmanInstitut Teknologi Sepuluh NovemberUniversitas BrawijayaUniversitas Pakuan BogorUniversitas Ibn Khaldun BogorUniversitas Budi LuhurPoliteknik Pos IndonesiaPoliteknik Negeri JakartaUniversitas Pendidikan IndonesiaUniversitas Islam IndonesiaInstitut Bisnis dan Informatika Stikom SurabayaUniversitas MulawarmanUniversitas GunadarmaUniversitas TarumanegaraSekolah Tinggi Teknik - Perusahaan Listrik NegaraUniversitas Muhammadiyah SukabumiSTMIK RaharjaUniversitas TrilogiLainnyaUniversitas IndonesiaInstitut Pertanian BogorUniversitas Muhammadiyah MalangInstitut Teknologi PLNUniversitas AndalasUniversitas Muhammadiyah JakartaUniversitas Pembangunan Nasional Veteran YogyakartaUniversitas PGRI SemarangUniversitas Islam Negeri Sunan Gunung Djati BandungUniversitas LampungUniversitas Mercu BuanaPoliteknik Negeri MalangUniversitas PGRI IndraprastaUniversitas PadjajaranPoliteknik Negeri SriwijayaSTMIK MikroskilUniversitas YarsiUniversitas NasionalPresident UniversityUniversitas SurabayaUniversitas Islam Negeri Syarif Hidayatullah JakartaUniversitas Pembangunan Nasional Veteran SurabayaUniversitas CiputraUniversitas Sunan KalijagaUniversitas DiponegoroUniversitas Ahmad DahlanUniversitas Amikom YogyakartaPoliteknik Pertanian Negeri SamarindaUniversitas Dian NuswantoroUniversitas Negeri JakartaUniversitas SriwijayaPoliteknik CaltexUniversitas Indraprasta PgriSTMIK Ikmi CirebonInstitut Bisnis dan Informatika Kwik Kian GieUniversitas Muhammadiyah YogyakartaUniversitas TelkomUniversitas Gadjah MadaUniversitas Kristen Satya WacanaInstitut Teknologi DelSTMIK Pasim Al-FathUniversitas Teknologi YogyakartaInstitut Teknologi Nasional MalangUniversitas PamulangInstitut KalbisUniversitas SingaperbangsaUniversitas Kristen Duta WacanaUniversitas Bina NusantaraSTMIK Asia MalangUniversitas Darma PersadaUniversitas Muhammadiyah PurwokertoSTMIK Widya PratamaUniversitas Negeri YogyakartaInstitut Teknologi BandungUniversitas UdayanaUniversitas Bina Sarana InformatikaPoliteknik Negeri BandungUniversitas BengkuluUniversitas Atma JayaUniversitas Putra Indonesia YPTK PadangUniversitas Sumatra Utara' or . = 'Pilih UniversitasUniversitas StikubankInstitut Sains dan Teknologi Al KamalUniversitas Sanata DharmaUniversitas Kristen MaranathaUniversitas JemberPoliteknik Elektronika Negeri SurabayaSTMIK Nusa MandiriUniversitas Teknologi MataramUniversitas Jendral SoedirmanInstitut Teknologi Sepuluh NovemberUniversitas BrawijayaUniversitas Pakuan BogorUniversitas Ibn Khaldun BogorUniversitas Budi LuhurPoliteknik Pos IndonesiaPoliteknik Negeri JakartaUniversitas Pendidikan IndonesiaUniversitas Islam IndonesiaInstitut Bisnis dan Informatika Stikom SurabayaUniversitas MulawarmanUniversitas GunadarmaUniversitas TarumanegaraSekolah Tinggi Teknik - Perusahaan Listrik NegaraUniversitas Muhammadiyah SukabumiSTMIK RaharjaUniversitas TrilogiLainnyaUniversitas IndonesiaInstitut Pertanian BogorUniversitas Muhammadiyah MalangInstitut Teknologi PLNUniversitas AndalasUniversitas Muhammadiyah JakartaUniversitas Pembangunan Nasional Veteran YogyakartaUniversitas PGRI SemarangUniversitas Islam Negeri Sunan Gunung Djati BandungUniversitas LampungUniversitas Mercu BuanaPoliteknik Negeri MalangUniversitas PGRI IndraprastaUniversitas PadjajaranPoliteknik Negeri SriwijayaSTMIK MikroskilUniversitas YarsiUniversitas NasionalPresident UniversityUniversitas SurabayaUniversitas Islam Negeri Syarif Hidayatullah JakartaUniversitas Pembangunan Nasional Veteran SurabayaUniversitas CiputraUniversitas Sunan KalijagaUniversitas DiponegoroUniversitas Ahmad DahlanUniversitas Amikom YogyakartaPoliteknik Pertanian Negeri SamarindaUniversitas Dian NuswantoroUniversitas Negeri JakartaUniversitas SriwijayaPoliteknik CaltexUniversitas Indraprasta PgriSTMIK Ikmi CirebonInstitut Bisnis dan Informatika Kwik Kian GieUniversitas Muhammadiyah YogyakartaUniversitas TelkomUniversitas Gadjah MadaUniversitas Kristen Satya WacanaInstitut Teknologi DelSTMIK Pasim Al-FathUniversitas Teknologi YogyakartaInstitut Teknologi Nasional MalangUniversitas PamulangInstitut KalbisUniversitas SingaperbangsaUniversitas Kristen Duta WacanaUniversitas Bina NusantaraSTMIK Asia MalangUniversitas Darma PersadaUniversitas Muhammadiyah PurwokertoSTMIK Widya PratamaUniversitas Negeri YogyakartaInstitut Teknologi BandungUniversitas UdayanaUniversitas Bina Sarana InformatikaPoliteknik Negeri BandungUniversitas BengkuluUniversitas Atma JayaUniversitas Putra Indonesia YPTK PadangUniversitas Sumatra Utara')]</value>
      <webElementGuid>e6d5b2a5-3f44-4629-af9e-67afdda5aeb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
