<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PilihGelar</name>
   <tag></tag>
   <elementGuidId>a4d5400c-2186-4f43-9c1d-fb702380283e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='degree']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#degree</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f7303626-0a71-4178-b4c9-471fdf37d773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>degree</value>
      <webElementGuid>a1d438cc-4036-4133-bc27-63d8bcb46ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>degree</value>
      <webElementGuid>ad26e574-3c13-41ce-8498-b4f8ba6969d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block flex-1 border-0 bg-transparent py-[14px] px-5 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-base sm:leading-6</value>
      <webElementGuid>a6717ce3-503b-4354-b9a8-329425349ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih GelarD3S1S2S3</value>
      <webElementGuid>6f2592dc-484f-411a-9894-45aa4a9d2133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;degree&quot;)</value>
      <webElementGuid>ccb7a9da-5a98-4c25-9a34-2bcf410f6ec1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='degree']</value>
      <webElementGuid>d41dc498-aa6c-4673-91a9-f7f491da7264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/div[2]/div[2]/div/div[3]/div/div/select</value>
      <webElementGuid>cc77edd3-3817-4e6a-a3f8-91cb059f432b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::select[1]</value>
      <webElementGuid>a8b26c1d-ad9a-443b-ab6c-e8cf8cf5d73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::select[1]</value>
      <webElementGuid>1e560607-776d-4b52-90ed-d72551a83379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footer'])[1]/preceding::select[1]</value>
      <webElementGuid>4bbede56-b484-4e4d-b8ad-8ba7798fb91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>55c4aa36-6e94-4f58-8afa-b7465d3d1d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'degree' and @name = 'degree' and (text() = 'Pilih GelarD3S1S2S3' or . = 'Pilih GelarD3S1S2S3')]</value>
      <webElementGuid>426836ac-d549-4fa8-8841-7b40bc4fdb2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
