<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PilihJurusan</name>
   <tag></tag>
   <elementGuidId>8e970973-3961-4cda-8914-ce4c992e5267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='major']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#major</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cb6c9091-e2ec-45f5-ae08-1c4ed5127eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>major</value>
      <webElementGuid>ffb54e1f-5a2a-447d-950c-5fa57ab28471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>major</value>
      <webElementGuid>8ea8cf4f-f31b-4d33-8193-361663414555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full px-3 py-[14px] bg-gray-50 border border-gray-300 rounded-lg</value>
      <webElementGuid>029d8391-1197-4089-9599-6d6af276d1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih JurusanIlmu KomputerTeknik ElektroTeknik TelekomunikasiStatistikaTeknik MesinTeknik KomputerFisikaSistem KomputerInformatikaTeknik IndustriHubungan MasyarakatLainnyaSistem InformasiMatematikaTeknik InformatikaManajemen InformatikaTeknik FisikaRekayasa Perangkat LunakTeknik Kimia</value>
      <webElementGuid>9263cc60-bffd-4a93-a506-a839706bda7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;major&quot;)</value>
      <webElementGuid>7fab9b7a-a0e1-44a4-bf91-c5dcb6b9cf2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='major']</value>
      <webElementGuid>08ac9710-05f5-4b39-95ea-9fcb575333f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/form/div[2]/div[2]/div/div[2]/div/select</value>
      <webElementGuid>612a1c1f-7db8-4f78-8727-ee8b94a3616a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::select[1]</value>
      <webElementGuid>34b3d422-6c18-4937-a945-c7e5380ab545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/preceding::select[1]</value>
      <webElementGuid>4c31293e-8d59-49e9-b17e-31f69d91e31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>b0030668-91f5-499c-8684-ac83d710ce16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'major' and @id = 'major' and (text() = 'Pilih JurusanIlmu KomputerTeknik ElektroTeknik TelekomunikasiStatistikaTeknik MesinTeknik KomputerFisikaSistem KomputerInformatikaTeknik IndustriHubungan MasyarakatLainnyaSistem InformasiMatematikaTeknik InformatikaManajemen InformatikaTeknik FisikaRekayasa Perangkat LunakTeknik Kimia' or . = 'Pilih JurusanIlmu KomputerTeknik ElektroTeknik TelekomunikasiStatistikaTeknik MesinTeknik KomputerFisikaSistem KomputerInformatikaTeknik IndustriHubungan MasyarakatLainnyaSistem InformasiMatematikaTeknik InformatikaManajemen InformatikaTeknik FisikaRekayasa Perangkat LunakTeknik Kimia')]</value>
      <webElementGuid>dfaf3661-e403-4765-ab2c-1e985de1771d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
